ZealTravelWebsite/ZealTravel.Backoffice.Web/Models/Agency/Booking/PrintPopupResponse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZealTravel.Backoffice.Web.Models.Agency.Booking
{
    public class PrintPopupResponse
    {
        public string? ReportTableHTML { get; set; }
        public string BookingRef { get; set; }
        public string Pax_SegmentId { get; set; }
        public string? SalesTable { get; set; }
        public string? Hdntktdetails { get; set; }
        public string HdnhostName { get; set; }
        public decimal? Discount { get; set; }
        public decimal? Tax { get; set; }
        public bool ShowLogo { get; set; } = true;
        public bool HideFare { get; set; } = false;
        public bool IsSingleFare { get; set; } = false;
        public string? CompanyID { get; set; }
        public string? PNR { get; set; }
        public string? TicketNumber { get; set; }
        public string? PassengerName { get; set; }
        public string SingleFare { get; set; }
        public string? BookingReference { get; set; }
    }
}

ZealTravelWebsite/ZealTravel.Backoffice.Web/Controllers/AgencyController.cs
using Microsoft.AspNetCore.Mvc;
using ZealTravel.Application.AgencyManagement.Queries;
using ZealTravel.Domain.Interfaces.Handlers;
using System.Linq;
using System.Threading.Tasks;
using System;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using ZealTravel.Application.UserManagement.Handlers;
using ZealTravel.Application.UserManagement.Queries;
using ZealTravel.Domain.Data.Models;
using ZealTravel.Backoffice.Web.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using ZealTravel.Application.AgencyManagement.Command;
using ZealTravel.Application.UserManagement.Commands;
using ZealTravel.Common.Helpers;
using AutoMapper;
using Microsoft.Identity.Client;
using log4net.Core;

namespace ZealTravel.Backoffice.Web.Controllers
{
    [Authorize]
    public class AgencyController : Controller
    {
        private readonly IHandlesQueryAsync<SearchAgencyTextQuery, List<SearchAgencyListData>> _searchAgencyBySearchTextQueryHandler;
        private readonly IHandlesQueryAsync<GetStatesQuery, List<GstStates>> _getStatesQueryHandler;
        private readonly IHandlesQueryAsync<GetCitiesByStateQuery, List<CityState>> _getCitiesByStateQueryHandler;
        private readonly ILogger<AccountController> _logger;
        private readonly IHandlesQueryAsync<GetCompanyProfileQuery, CompanyProfileData> _getCompanyProfileHandler;
        private readonly IHandlesCommandAsync<CompanyProfileCommand> _updateCompanyProfileHandler;
        private readonly IMapper _mapper;
        private readonly IHandlesCommandAsync<UpdateLogoCommand> _updateLogoCommandHandler;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IHandlesQueryAsync<AgencyListBySearchTextQuery, List<string>> _getAgencyListbySerachTextQueryHandler;
        private readonly IHandlesQueryAsync<CompanyIdByAccountIdQuery, string> _getCompanyIDByAccountIDQueryHandler;
        private readonly IHandlesQueryAsync<GetAvailableBalanceQuery, decimal> _getAvailableBalanceQueryHandler;
        private readonly IHandlesQueryAsync<GetAgencyBalanceTransactionEventQuery, List<GetAgencyBalanceTransactionEvents>> _getCompanyEventDetailHandler;
        private readonly IHandlesCommandAsync<UpdateBalanceTransactionCommand> _balanceTransactionCommandHandler;
        private readonly IHandlesQueryAsync<VerifyAgentBookingQuery, bool> _verifyAgentQueryHandler;

        public AgencyController(
            IHandlesQueryAsync<SearchAgencyTextQuery, List<SearchAgencyListData>> searchAgencyBySearchTextQueryHandler,
            IHandlesQueryAsync<GetStatesQuery, List<GstStates>> getStatesQueryHandler,
            IHandlesQueryAsync<GetCitiesByStateQuery, List<CityState>> getCitiesByStateQueryHandler,
            ILogger<AccountController> logger,
            IHandlesQueryAsync<GetCompanyProfileQuery, CompanyProfileData> getCompanyProfileQueryHandler,
            IHandlesCommandAsync<CompanyProfileCommand> updateCompanyProfileHandler,
            IMapper mapper,
            IHandlesCommandAsync<UpdateLogoCommand> updateLogoCommandHandler,
            IWebHostEnvironment webHostEnvironment,
            IHandlesQueryAsync<AgencyListBySearchTextQuery, List<string>> getAgencyListbySerachTextQueryHandler,
            IHandlesQueryAsync<CompanyIdByAccountIdQuery, string> getCompanyIDByAccountIDQueryHandler,
            IHandlesQueryAsync<GetAvailableBalanceQuery, decimal> getAvailableBalanceQueryHandler,
            IHandlesQueryAsync<GetAgencyBalanceTransactionEventQuery, List<GetAgencyBalanceTransactionEvents>> getCompanyEventDetailHandler,
            IHandlesCommandAsync<UpdateBalanceTransactionCommand> balanceTransactionCommandHandler,
            IHandlesQueryAsync<VerifyAgentBookingQuery, bool> verifyAgentQueryHandler
            )
        {
            _searchAgencyBySearchTextQueryHandler = searchAgencyBySearchTextQueryHandler;
            _getStatesQueryHandler = getStatesQueryHandler;
            _getCitiesByStateQueryHandler = getCitiesByStateQueryHandler;
            _logger = logger;
            _getCompanyProfileHandler = getCompanyProfileQueryHandler;
            _updateCompanyProfileHandler = updateCompanyProfileHandler;
            _mapper = mapper;
            _updateLogoCommandHandler = updateLogoCommandHandler;
            _webHostEnvironment = webHostEnvironment;
            _getAgencyListbySerachTextQueryHandler = getAgencyListbySerachTextQueryHandler;
            _getCompanyIDByAccountIDQueryHandler = getCompanyIDByAccountIDQueryHandler;
            _getAvailableBalanceQueryHandler = getAvailableBalanceQueryHandler;
            _getCompanyEventDetailHandler = getCompanyEventDetailHandler;
            _balanceTransactionCommandHandler = balanceTransactionCommandHandler;
            _verifyAgentQueryHandler = verifyAgentQueryHandler;
        }


        [HttpGet]
        [Route("agency/searchAgency")]
        public async Task<IActionResult> GetAgencyList(string searchText)
        {
            try
            {
                var accountIdString = User.FindFirstValue("AccountID");

                if (string.IsNullOrEmpty(accountIdString) || !int.TryParse(accountIdString, out int accountId))
                {
                    return BadRequest("Invalid or missing Account ID in session.");
                }
                //var accountId = 101;
                var query = new AgencyListBySearchTextQuery { AccountId = accountId, SearchText = searchText };
                var agencies = await _getAgencyListbySerachTextQueryHandler.HandleAsync(query);

                if (!agencies.Any())
                {
                    return NotFound("No agencies found with the provided search text.");
                }

                return Ok(agencies);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal Server Error: {ex.Message}");
            }
        }

        public async Task<IActionResult> GetAllStates()
        {
            var query = new GetStatesQuery();
            var cityStates = await _getStatesQueryHandler.HandleAsync(query);

            if (cityStates == null || !cityStates.Any())
            {
                return NotFound("No states found.");
            }

            var states = cityStates.Select(state => new
            {
                StateCode = state.StateCode,
                StateName = state.State
            }).ToList();

            return Ok(states);
        }

        public async Task<IActionResult> GetCityByState(string stateName = null)
        {
            var query = new GetCitiesByStateQuery(stateName);
            var cityStates = await _getCitiesByStateQueryHandler.HandleAsync(query);

            if (cityStates == null || !cityStates.Any())
            {
                return NotFound("No states found.");
            }

            return Ok(new { cities = cityStates });
        }

        [HttpGet]
        [Route("agency/search")]
        public IActionResult SearchAgency()
        {
            var model = new SearchAgencyResponse
            {
                AgencyData = new List<SearchAgencyData>()
            };
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("agency/search")]
        public async Task<IActionResult> SearchAgency(SearchAgencyResponse model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var companyId = User.FindFirst("CompanyId")?.Value;

            if (string.IsNullOrEmpty(companyId))
            {
                ModelState.AddModelError(string.Empty, "Unable to retrieve company ID from session.");
                return View(model);
            }
            if (string.IsNullOrWhiteSpace(model.CompanyName) &&
        string.IsNullOrWhiteSpace(model.AccountId.ToString()) &&
        string.IsNullOrWhiteSpace(model.State) &&
        string.IsNullOrWhiteSpace(model.City))
            {
                model.ShowNoInputError = true; // Set the flag
                return View(model); ;
            }

            var queryStateSearch = new GetStatesQuery();
            var cityStates = await _getStatesQueryHandler.HandleAsync(queryStateSearch);

            if (cityStates == null || !cityStates.Any())
            {
                ModelState.AddModelError(string.Empty, "No states found.");
                return View(model);
            }

            if (string.IsNullOrEmpty(model.State))
            {
                model.State = null;
            }

            var selectedState = !string.IsNullOrEmpty(model.State)
              ? cityStates.FirstOrDefault(state => state.StateCode == model.State)
              : null;

            var query = new SearchAgencyTextQuery
            {
                AccountId = model.AccountId,
                CompanyID = companyId,
                CompanyName = model.CompanyName,
                State = selectedState?.State,
                City = model.City
            };

            var agencies = await _searchAgencyBySearchTextQueryHandler.HandleAsync(query);

            if (agencies == null || !agencies.Any())
            {
                ModelState.AddModelError(string.Empty, "No agencies found for the given criteria.");
                return View(model);
            }

            model.AgencyData = agencies.Select((agency, index) => new SearchAgencyData
            {
                ID = index + 1,
                CompanyName = agency.CompanyName,
                AccountID = agency.AccountID,
                City = agency.City,
                UserType = agency.UserType,
                Active_Status = agency.Active_Status,
                EventTime = agency.EventTime,
                AvailableBalance = agency.AvailableBalance
            }).ToList();

            return View(model);
        }

        [HttpGet]
        [Authorize]
        [Route("agency/Profile")]

ZealTravelWebsite/ZealTravel.Backoffice.Web/Views/Agency/SearchAgency.cshtml
@model ZealTravel.Backoffice.Web.Models.SearchAgencyResponse
@inject IConfiguration Configuration
@{
    Layout = "~/Views/Master.cshtml";
    ViewData["Title"] = "SearchAgency";
}

<link href="~/assets/css/newd.css" rel="stylesheet" />
<link href="~/assets/css/custom.css" rel="stylesheet" />
<link href="~/assets/css/newdashB.css" rel="stylesheet" />
<link href="~/assets/css/ValidationEngine.css" rel="stylesheet" />
<link href="~/assets/css/colortheme.css" rel="stylesheet" />
<link href="~/assets/css/AdminLTE.css" rel="stylesheet" />
<link href="~/assets/css/searchAgency.css" rel="stylesheet" />


<div class="wrapper">
    <div class="content-wrapper" style="min-height: 1324px;">
        <section class="content" style="padding: 0px;">



            <div class="container-fluid">
                <div style="width: 100%; margin: 0 auto; ">
                    <div class="col-md-12 col-xs-12 offset-0">
                        <h5 class="reportminheader"><i class="fa fa-search wredcolo reportminicon" aria-hidden="true" style=""></i> Search Company</h5>
                    </div>
                </div>
            </div>

                    <div class="col-md-12 col-xs-12">

                        <div class="col-md-12 col-xs-12 boxshdr " style="margin-top:5px; margin-bottom:5px;">
                            @using (Html.BeginForm("SearchAgency", "Agency", FormMethod.Post, new { id = "SearchAgency.cshtml" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="col-md-12 col-sm-12 col-xs-12 offset-0">


                                    <div class="col-md-12 col-sm-12 col-xs-12 offset-0">
                                        <div class="col-md-6 col-sm-6 col-xs-12 offset-0 m-top-10">
                                            <div class="col-md-4 col-sm-4 col-xs-12"><strong>Company Name </strong></div>
                                            <div class="col-md-8 col-sm-8 col-xs-12">
                                                @Html.TextBoxFor(m => m.CompanyName, new
                                                    {
                                                        @class = "form-control",
                                                        @placeholder = "Company Name"
                                                    })
                                            </div>

                                        </div>
                                <div class="col-md-6 col-sm-6 col-xs-12 offset-0 m-top-10">
                                    <div class="col-md-4 col-sm-4 col-xs-12"><strong>Account ID </strong></div>
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        @Html.TextBoxFor(m => m.AccountId, new { @class = "form-control", @placeholder = "Account ID" })
                                    </div>

                                </div>


                                    </div>

                                    <div class="col-md-12 col-sm-12 col-xs-12 offset-0">
                                        <div class="col-md-6 col-sm-6 col-xs-12 offset-0 m-top-10">
                                            <div class="col-md-4 col-sm-4 col-xs-12"><strong>State </strong></div>
                                            <div class="col-md-8 col-sm-8 col-xs-12">
                                                @Html.DropDownListFor(m => m.State, new SelectList(Enumerable.Empty<SelectListItem>(), "Value", "Text"), "Select State", new { @class = "form-control", @id = "stateDropdown" })
                                            </div>
                                        </div>

                                        <div class="col-md-6 col-sm-6 col-xs-12 offset-0 m-top-10">
                                            <div class="col-md-4 col-sm-4 col-xs-12"><strong>City</strong></div>
                                            <div class="col-md-8 col-sm-8 col-xs-12">
                                                @Html.DropDownListFor(m => m.City, new SelectList(Enumerable.Empty<SelectListItem>(), "Value", "Text"), "Select City", new { @class = "form-control", @id = "cityDropdown"})
                                            </div>

                                        </div>
                                    </div>


                                    <div class="col-md-12 col-sm-12 col-xs-12 m-top-10 text-center" style="margin-top: 15px;">
                                <input type="submit" class="btn btn-primary" value="Search" style="background: #04c !important; color: #fff !important; font-size: 19px; padding: 9px 12px; box-shadow: 0px 0px 14px #0000005e; font-family: 'Quicksand', sans-serif" />
                                    </div>
                                </div>
                            }



                            <div class="col-md-12 col-sm-12 col-xs-12 brdr-cls pdng-btm m-top-10 offset-0">


                                <div class="col-md-12 col-xs-12 table-responsive" style="padding-left: 0px; padding-right: 0px; margin-top: -6px;">

                                    <table class="defaultText table-responsive table table-striped table-bordered table-hover" style="width: 100%" cellspacing="1" cellpadding="4" border="0" id="Table1">
                                @if (Model.ShowNoInputError)
                                {
                                    <tr style="width: 100%; height: 30px;" id="ct0">
                                        <td colspan="8" class="col-md-12 col-xs-12">
                                            <h5 class="text-center" style="color: Red;">Please provide at least one search Criteria.</h5>
                                        </td>
                                    </tr>
                                }
                                else if (Model.AgencyData != null && Model.AgencyData.Any())
                                {
                                    <thead>
                                        <tr class="hg">
                                            <th>#</th>
                                            <th>Company</th>
                                            <th>Account No</th>
                                            <th>City</th>
                                            <th>User Type</th>
                                            <th>Status</th>
                                            <th>Registration Date</th>
                                            <th>Balance</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var agency in Model.AgencyData)
                                        {
                                            <tr id="tablerow_@agency.ID">
                                                <td>@agency.ID</td>
                                                <td>
                                                    <a class="txt_blue" id="comp_@agency.ID" accesskey="@agency.CompanyName,@agency.AccountID" onclick="modifycomp(this)" style="cursor: pointer">
                                                        @agency.CompanyName
                                                    </a>
                                                </td>
                                                <td id="Acid_@agency.ID" class="ui-border-wo-topleft" align="center">@agency.AccountID</td>
                                                <td id="cty_@agency.ID" class="ui-border-wo-topleft" align="center">@agency.City</td>
                                                <td id="agtyp_@agency.ID" class="ui-border-wo-topleft" align="center">@agency.UserType</td>
                                                <td id="stat_@agency.ID" class="ui-border-wo-topleft" align="center">@agency.Active_Status</td>
                                                <td id="regdat_@agency.ID" class="ui-border-wo-topleft" align="center">@agency.EventTime</td>
                                                <td id="chklmt_@agency.ID" class="ui-border-wo-topleft" align="center">@agency.AvailableBalance</td>
                                            </tr>
                                        }
                                    </tbody>
                                }
                                else
                                {
                                    <tr style="width: 100%; height: 30px;" id="ct0">
                                        <td colspan="8" class="col-md-12 col-xs-12">
                                            <h5 class="text-center" style="color: Red;">No Record Found!</h5>
                                        </td>
                                    </tr>
                                }

                                    </table>

                                </div>
                            </div>

                        </div>
                    </div>

                    <script type="text/javascript">
                        Sys.Application.add_load(LoadScript);
                    </script>


        </section>
    </div>
</div>

<script type="text/javascript">
    function LoadScript() {
        //   $(document).ready(function () {

        debugger;
        var d = new Date();
        var month = d.getMonth() + 1;
        var day = d.getDate();
        var year = d.getFullYear();
        var dateNow = year + "-" + month + "-" + day;
        $(".datetopic").datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            todayHighlight: true,
            //clearBtn: true,
            orientation: 'bottom',
            defaultDate: dateNow
        });

        // });
    }
    function chklimit(abc) {
        debugger;
        var yroom = 1, user = {}, ucpol = "";
        try {
            var dtta = abc.accessKey.split(",");
            user.msgQual = dtta[1];
            ucpol = $.ajax({ type: "POST", url: "SearchAgency.aspx/getagentbal", async: false, data: '{user: ' + JSON.stringify(user) + '}', contentType: "application/json; charset=utf-8", dataType: "json", success: function (response) { } });

            var totaldata1 = JSON.parse(ucpol.responseText).d.split(',');
            if (totaldata1 != "" && totaldata1 != null) {
                document.getElementById("Compnynm").innerHTML = dtta[0];
                document.getElementById("Accontiid").innerHTML = dtta[1];
                document.getElementById("Amnt").innerHTML = totaldata1[0];
                document.getElementById("cty").innerHTML = dtta[2];
                document.getElementById("agnttype").innerHTML = dtta[3];

                $("#myModal").modal('show');
            }
        }
        catch (e) {
        }
    }
    function modifycomp(abc) {
        debugger;
        var data = abc.accessKey.split(",")[1];
        location.href = "/agency/profile?value=" + btoa(data);
    }
</script>




<div class="modal fade" id="myModal" role="dialog" style="margin-top: 0%; pointer-events: none;">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content" style="pointer-events: auto; top:90px; ">
            <div class="modal-header" style="padding: 8px;">
                <p style="text-align: center; color: #fff; margin-bottom: 0px; font-size: 17px;">DETAIL</p>
                <button type="button" class="close uc ptpop" data-dismiss="modal" style="padding: 5px 10px 5px 10px !important;margin-top: 9.5%;margin-left: 75%;color: #fff;">&times;</button>
            </div>
            <div class="modal-body hg" style="padding: 0%;">

                <div class="panel-body panel-body1" style="border: 1px solid #fff;">
                    <span class="col-md-4 col-xs-4 offset-0">Company Name </span>
                    <span class="col-md-8 col-xs-8" id="Compnynm"></span>
                </div>

                <div class="panel-body panel-body1" style="border: 1px solid #fff;">
                    <span class="col-md-4 col-xs-4 offset-0">
                        Account Id
                    </span><span class="col-md-8 col-xs-8" id="Accontiid"></span>
                </div>

                <div class="panel-body panel-body1" style="border: 1px solid #fff;">
                    <span class="col-md-4 col-xs-4 offset-0">
                        Amount
                    </span><span class="col-md-8 col-xs-8" id="Amnt"></span>
                </div>
                <div class="panel-body panel-body1" style="border: 1px solid #fff;">
                    <span class="col-md-4 col-xs-4 offset-0">
                        City
                    </span><span class="col-md-8 col-xs-8" id="cty"></span>
                </div>

                <div class="panel-body panel-body1" style="border: 1px solid #fff;">
                    <span class="col-md-4 col-xs-4 offset-0">
                        Agent Type
                    </span><span class="col-md-8 col-xs-8" id="agnttype"></span>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<script src="~/assets/js/registerAgency.js"></script>
<script src="~/assets/js/registration.js"></script>
<script src="~/assets/js/onlineformvalidationengine.js"></script>